language: ruby
script: bundle _1.7.9_ exec rake
before_install:
  - gem install bundler -v "$BUNDLER_VERSION"
install:
  - travis_retry bundle _1.7.9_ install
addons:
    code_climate:
        repo_token: 3a5d0d815b7e9bc2c6b4608f74babd935d43fa564cd9041944dfd221f593a4db
matrix:
  include:
    - gemfile: Gemfile
      rvm: 2.6.5
      env:
        BUNDLER_VERSION='1.7.9'

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
