language: ruby
script: bundle exec rspec spec
before_install:
  - rvm @global do gem uninstall bundler --all --force --executables
  - gem uninstall bundler --all --force --executables
  - gem install bundler -v "$BUNDLER_VERSION"
bundler_args: --without development
matrix:
  include:
    - gemfile: Gemfile
      rvm: 2.2.1
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.8.0'
    - gemfile: Gemfile
      rvm: 2.1.4
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.8.0'
    - gemfile: Gemfile
      rvm: 2.0.0
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.8.0'
    - gemfile: gemfiles/vagrant_1.7.gemfile
      rvm: 2.2.1
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.8.0'
    - gemfile: gemfiles/vagrant_1.7.gemfile
      rvm: 2.1.4
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.8.0'
    - gemfile: gemfiles/vagrant_1.7.gemfile
      rvm: 2.0.0
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.8.0'
    - gemfile: gemfiles/vagrant_1.7.gemfile
      rvm: 1.9.3
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.8.0'
    - gemfile: gemfiles/vagrant_1.6.gemfile
      rvm: 2.2.1
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.7.0'
    - gemfile: gemfiles/vagrant_1.6.gemfile
      rvm: 2.1.4
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.7.0'
    - gemfile: gemfiles/vagrant_1.6.gemfile
      rvm: 2.0.0
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.7.0'
    - gemfile: gemfiles/vagrant_1.6.gemfile
      rvm: 1.9.3
      env:
        BUNDLER_VERSION='>= 1.5.2, < 1.7.0'
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
