language: ruby
rvm:
    - "1.9.2"
    - "1.9.3"
    - "2.0.0"
    - "2.1.4"
    - "2.2.1"
# env: VAGRANT_VERSION="v1.7.2"
script: bundle exec rspec spec
before_install: gem install bundler -v 1.10.6
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
